<?php
/**
 *
 * 用户金额
 * User: lc
 * Date: 2019-05-14 14:30
 */

namespace app\api\controller\user;


use app\api\controller\BankCard;
use app\api\controller\Controller;
use app\common\library\wechat\WxPay;
use app\common\model\PriceLog;

class Price extends Controller
{
    protected $user;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = $this->getUser();   // 用户信息
    }

    public function lists()
    {
        $model = new PriceLog();
        $filer = [];
        $filer['user_id'] = $this->user['user_id'];
        $list = $model->where($filer)->paginate(15);
        return $this->renderSuccess($list);
    }


    public function pay_bank()
    {
        $price = $this->request->post('price');
        $bank_id = $this->request->post('bank_id');
        if($this->user['price'] < $price){
            return $this->renderError('提现金额不能超过'.$this->user['price']);
        }
        $bank = BankCard::get($bank_id);
        if(!$bank){
            return $this->renderError('选择提现银行卡');
        }
        $wxConfig = Setting::getItem('payment');
        $WxPay = new WxPay($wxConfig['engine']['wechat']);
        if($WxPay->pay_bank($this->user,$price,$bank)){
            return $this->renderError('提现成功');
        }
        return $this->renderError('提现失败');
    }

    /**
     * 财富管理
     * @param $dataType 天数
     * @return array
     */
    public function wealth_manage($dataType)
    {
        $date_list = $this->getDate($dataType);
        $data = [];
        foreach ($date_list as $v){
            $data[$v] = $this->priceList($v);
        }
        return $this->renderSuccess($data);
    }

    /**
     * 用户每天收入
     * @param $date 日期 2018-05-18
     * @return float|int
     */
    private function priceList($date)
    {
        $start = strtotime($date);
        $end = $start + 86400 -1;
        $total = PriceLog::where('user_id',$this->user['user_id'])->where('create_time','BETWEEN',[$start,$end])->sum('price');
        return sprintf("%01.2f",$total);
    }

    /**
     * 获取最近的日期
     * @param $num
     * @return array
     */
    private function getDate($num)
    {
        $data = [];
        $time = time();
        for($i = 0; $i < $num;$i++){
            $data[] = date('Y-m-d',$time-($i*86400));
        }
        return $data;
    }
}